<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy</title>
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="css/custom.css">
</head>
<body class="bg-black">
    <div class="max-w-6xl mx-auto px-6">
        <?php include("navbar.php") ?>
    </div>
    <main>
        <section class="py-10 md:pt-28 md:pb-32">
            <div class="max-w-6xl mx-auto px-6">
                <div class="text-center mb-48">
                    <h2 class="text-4xl lg:text-5xl font-body font-bold text-white mb-8">Privacy Policy</h2>
                    <p class="max-w-2xl mx-auto text-brand-gray-light-1 text-xl lg:text-2xl">Below are our legal requirements and policies that guide our organisation to ensure the benefits of the users</p>
                </div>
                <div class="text-brand-gray-light-1 text-lg">
                    <h3 class="text-3xl lg:text-4xl font-body font-bold text-white mb-8">Definitions</h3>
                    <p class="mb-8">Personal Data Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                    <p class="mb-8">Usage Data Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                    <p class="mb-8">Cookies Cookies are small files stored on your device (computer or mobile device).</p>
                    <p class="mb-8">Data Controller Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
                    <p class="mb-8">Data Processors (or Service Providers) Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
                    <p class="mb-8">Data Subject (or User) Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
                    <p class="mb-8">Information collection and use
                    We collect several different types of information for various purposes to provide and improve our Service to you.</p>
        
                    <h3 class="text-white text-3xl lg:text-4xl font-body font-bold mb-8">Types of Data Collected</h3>
                    <p class="mb-8">Personal Data While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
                    <div class="mb-8">
                        <p>Email address</p>   
                        <p>First name and last name</p>   
                        <p>Phone number</p>   
                        <p>Address, State, Province, ZIP/Postal code, City</p>   
                        <p>Cookies and Usage Data</p>   
                        <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.</p>   
                    </div>
                    <p class="mb-8">Usage Data We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                    <p class="mb-8">Location Data We may use and store information about your location if you give us permission to do so ("Location Data"). We use this data to provide features of our Service, to improve and customize our Service. You can enable or disable location services when you use our Service at any time by way of your device settings.</p>    
                    <p class="mb-8">Tracking Cookies Data We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p> 
                    <p class="mb-8">Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.</p>  
                    <p class="mb-8">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>  

                    <h3 class="text-white text-3xl lg:text-4xl font-body font-bold mb-8">Examples of Cookies we use:</h3>
                    <p>Session Cookies. We use Session Cookies to operate our Service.
                    Preference Cookies. We use Preference Cookies to remember your preferences and various settings.
                    Security Cookies. We use Security Cookies for security purposes.
                    Advertising Cookies. Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</p>
                    <p>Use of data</p>
                    <p class="mb-8">We uses the collected data for various purposes:</p>
                    <div class="mb-8">
                        <p>To provide and maintain our Service</p>
                        <p>To notify you about changes to our Service</p>
                        <p>To allow you to participate in interactive features of our Service when you choose to do so</p>
                        <p>To provide customer support</p>
                        <p>To gather analysis or valuable information so that we can improve our Service</p>
                        <p>To monitor the usage of our Service</p>
                        <p>To detect, prevent and address technical issues
                        To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information
                        Legal basis for processing personal data under the General Data Protection Regulation (GDPR)</p>
                        <p>If you are from the European Economic Area (EEA), Saint Bitts’ legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>
                    </div>
        
                    <h3 class="text-white text-3xl lg:text-4xl font-body font-bold mb-8">We may process your Personal Data because:</h3>
                    <p>We need to perform a contract with you
                    You have given us permission to do so
                    The processing is in our legitimate interests and it is not overridden by your rights to comply with the law</p>
                    <p>Retention of data</p>
                    <p class="mb-8">We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.</p>
                    <p class="mb-8">We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</p>   
        
                    <h3 class="text-white text-3xl lg:text-4xl font-body font-bold mb-8">Transfer of data</h3>
                    <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
                    <p class="mb-8">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
                    <p class="mb-8">We will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>   
                    <p class="mb-8">The right to access, update or delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you. The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete. The right to object. You have the right to object to our processing of your Personal Data. The right of restriction. You have the right to request that we restrict the processing of your personal information. The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format. The right to withdraw consent. You also have the right to withdraw your consent at any time where Saint Bitts relied on your consent to process your personal information.</p>   
                    <p class="mb-8">Please note that we may ask you to verify your identity before responding to such requests.</p>   
                    <p class="mb-8">You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>    
                    <p>Service providers</p>  
                    <p class="mb-8">We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p> 
                    <p class="mb-8">These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>  
                    <p class="mb-8">Analytics We may use third-party Service Providers to monitor and analyse the use of our Service.</p>
                    <p class="mb-8">Advertising We may use third-party Service Providers to show advertisements to you to help support and maintain our Service.</p>   
                    <p>Behavioral Remarketing We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based 
                </div>
            </div>
        </section>
    </main>
    <?php include("footer.php") ?>
</body>
</html>